---
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kubernetes
spec:
  api:
    sans:
      - kubernetes.local
  network:
    provider: custom
  featureGates:
    - name: UserNamespacesSupport
      enabled: true
  extensions:
    helm:
      charts:
        - name: cilium
          chartname: oci://registry-1.docker.io/sanselmechart/cilium
          namespace: kube-system
          order: 1
          version: 1.16.4
          values: |
            kubeProxyReplacement: true
            l2announcements:
              enabled: true
            gatewayAPI:
              enabled: true
            operator:
              replicas: 1
        - name: cni-resource
          chartname: oci://registry-1.docker.io/sanselmechart/cni-resource
          namespace: kube-system
          order: 1
          version: 0.1.0
          values: |
            cilium:
              pool:
                allowFirstLastIPs: "'No'"
              advert:
                l2:
                  enabled: true
                bgp:
                  enabled: false
              config:
                cluster:
                  enabled: false
                peer:
                  enabled: false
        - name: openebs
          chartname: oci://registry-1.docker.io/sanselmechart/openebs
          namespace: kube-system
          order: 2
          version: 3.10.0
          values: |
            analytics:
              enabled: false
            localprovisioner:
              hostpathClass:
                isDefaultClass: true
        - name: cert-manager
          chartname: oci://registry-1.docker.io/sanselmechart/cert-manager
          namespace: cert-manager
          order: 3
          version: v1.16.2
          values: |
            crds:
              enabled: true
        - name: trust-manager
          chartname: oci://registry-1.docker.io/sanselmechart/trust-manager
          namespace: trust-manager
          order: 3
          version: v0.13.0
        - name: cert-manager
          chartname: oci://registry-1.docker.io/sanselmechart/ca-clusterissuer
          namespace: cert-manager
          order: 3
          version: 0.2.0
          values: |
            manifests:
              clusterissuer: false
              selfsigned: true
        # - name: k8s-monitoring
        #   chartname: oci://registry-1.docker.io/sanselmechart/k8s-monitoring
        #   namespace: observability
        #   order: 3
        #   version: 1.6.11
        # - name: knative-operator
        #   chartname: oci://registry-1.docker.io/sanselmechart/knative-operator
        #   namespace: operators
        #   order: 3
        #   version: 0.3.0
  telemetry:
    enabled: false
